"""
Fetches Pexels stock images using search queries generated by the pipeline.
Returns up to 7 unique images across all queries.
"""
import asyncio
from app.tools.image_search import search_pexels_images
from app.schemas.image import ImageResult, ImageListResponse

_MAX_IMAGES = 7


async def get_images_for_post(
    topic: str,
    post_text: str,
    image_prompts: list[dict],
    search_query: str | None = None,
) -> ImageListResponse:
    """
    Fetch Pexels stock images.

    - If search_query is provided, search Pexels directly with that term (returns 7 results).
    - Otherwise, use the queries generated by the Pexels Image Searcher agent
      (3 queries × 3 results, deduplicated, capped at 7).

    image_prompts format: [{"query": "ai technology office", "style": "professional"}, ...]
    """
    if search_query:
        raw = await search_pexels_images(search_query, count=_MAX_IMAGES)
        images = [ImageResult(**img) for img in raw]
        if images:
            images[0].recommended = True
        return ImageListResponse(
            images=images,
            recommended_id=images[0].id if images else None,
        )

    # Use agent-generated queries; fall back to the raw topic
    queries = [p.get("query", topic) for p in image_prompts[:3] if p.get("query")]
    if not queries:
        queries = [topic]

    # Search all queries concurrently
    tasks = [search_pexels_images(q, count=3) for q in queries]
    results = await asyncio.gather(*tasks, return_exceptions=True)

    all_images: list[ImageResult] = []
    seen_ids: set[str] = set()

    for result in results:
        if not isinstance(result, list):
            continue
        for img in result:
            if img["id"] not in seen_ids and len(all_images) < _MAX_IMAGES:
                seen_ids.add(img["id"])
                all_images.append(ImageResult(**img))

    if all_images:
        all_images[0].recommended = True

    return ImageListResponse(
        images=all_images,
        recommended_id=all_images[0].id if all_images else None,
    )
